import type { TermLine, ChoiceConfig, ChoiceId, AtmVisualState } from './types';

export const CHOICES: Record<ChoiceId, ChoiceConfig> = {
  'panel-access': {
    prompt: 'SELECT PANEL ACCESS METHOD:',
    options: [
      { key: '1', label: 'Ebay Dyebold T-bar Key (SKU 001-0006522)', outcome: 'correct' },
      { key: '2', label: 'Crow bar', outcome: 'wrong', wrongReason: 'Vibration sensor triggered - tamper alarm dispatched to monitoring center' },
      { key: '3', label: 'Social Engineering - Wear DN field technician gear & badge', outcome: 'correct' },
    ],
  },
  'ethernet': {
    prompt: 'SELECT LOG HANDLING METHOD:',
    options: [
      { key: '1', label: 'Cut cable + insert RJ45 loopback plug', outcome: 'correct' },
      { key: '2', label: 'Cut cable only', outcome: 'partial', wrongReason: 'Buffered logs flushed to bank SIEM on reconnect - alert dispatched' },
      { key: '3', label: 'Leave cable intact', outcome: 'wrong', wrongReason: 'Live tamper log received by SIEM - police dispatched (ETA ~40s)' },
    ],
  },
  'alarm-sensor': {
    prompt: 'SELECT DOOR-ALARM BYPASS METHOD:',
    options: [
      { key: '1', label: 'Magnetic reed-switch clamp', outcome: 'correct' },
      { key: '2', label: 'Cut alarm sensor wire', outcome: 'wrong', wrongReason: 'Monitoring loop broken - tamper alarm triggered at central station' },
      { key: '3', label: 'Ignore sensor & hope nobody is watching', outcome: 'wrong', wrongReason: 'Door-open alert fired - units rolling (ETA ~40s)' },
    ],
  },
  'install-method': {
    prompt: 'SELECT MALWARE INSTALLATION METHOD:',
    options: [
      { key: '1', label: 'Remove the HDD and deploy Ploutus on NTFS partition', outcome: 'correct' },
      { key: '2', label: 'Boot from USB live OS and inject Ploutus', outcome: 'correct' },
      { key: '3', label: 'Use a Raspberry Pi black box', outcome: 'correct' },
    ],
  },
  'persist-method': {
    prompt: 'SELECT PERSISTENCE / EXIT METHOD:',
    options: [
      { key: '1', label: 'Reseal panel, restore sensor, power-cycle ATM', outcome: 'correct' },
      { key: '2', label: 'Leave panel ajar / skip reseal', outcome: 'wrong', wrongReason: 'Open cabinet spotted by passerby - silent alarm tripped' },
      { key: '3', label: 'Skip reboot - leave malware unloaded until next crash', outcome: 'wrong', wrongReason: 'Payload never loaded - ATM still clean; wasted op' },
    ],
  },
  'activate-method': {
    prompt: 'SELECT ACTIVATION METHOD:',
    options: [
      { key: '1', label: 'Plug USB keyboard + enter rotating activation code', outcome: 'correct' },
      { key: '2', label: 'Trigger dispense from the normal customer PIN screen', outcome: 'wrong', wrongReason: 'Customer UI has no jackpot path - failed attempt logged' },
      { key: '3', label: 'Call activation server from a phone next to the ATM', outcome: 'wrong', wrongReason: 'Cellular burst near vestibule flagged by fraud analytics' },
    ],
  },
};

export const CONTINUATIONS: Record<string, TermLine[]> = {
  'panel-access:1': [
    { t: 'out', text: '# t-bar 001-0006522 seated - latch released', s: 'ok' },
    { t: 'out', text: '# top-hat panel open - cavity exposed', s: 'ok' },
  ],
  'panel-access:3': [
    { t: 'out', text: '# social: DN badge accepted - escorted to ATM', s: 'warn' },
    { t: 'out', text: '# guard unlocked panel - internal access granted', s: 'ok' },
  ],
  'ethernet:1': [
    { t: 'cmd', text: 'ip link show eth0 | head -n2' },
    { t: 'out', text: '2: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500' },
    { t: 'out', text: '# wall jack: RJ45 loopback seated - SIEM stream dead', s: 'ok' },
  ],
  'ethernet:2': [
    { t: 'out', text: '# eth cut - NIC buffering locally (no loopback)', s: 'warn' },
    { t: 'out', text: '# WARNING: buffer flushes to SIEM on reconnect', s: 'warn' },
  ],
  'alarm-sensor:1': [
    { t: 'out', text: '# reed clamp on door sensor - reads CLOSED', s: 'ok' },
    { t: 'out', text: '# monitoring loop intact - no central-station hit', s: 'ok' },
  ],
  'install-method:1': [
    { t: 'cmd', text: 'lsblk | grep sdb' },
    { t: 'out', text: 'sdb  8:16  0  80G  0  disk  <- ATM HDD via USB-SATA', s: 'ok' },
    { t: 'cmd', text: 'ntfs-3g /dev/sdb1 /mnt/atm -o remove_hiberfile' },
    { t: 'out', text: 'Mounted /dev/sdb1 at /mnt/atm', s: 'ok' },
    { t: 'out', text: 'OS: Windows XP SP3 - Agilis XFS 3.20 confirmed', s: 'ok' },
    { t: 'cmd', text: 'ls /mnt/atm/Windows/System32/ | grep -iE "xfs|cdm"' },
    { t: 'out', text: 'MSXFS.dll' },
    { t: 'out', text: 'CDM_ServiceProvider.dll', s: 'ok' },
    { t: 'cmd', text: 'cp ~/ploutus/payload/svchost32.exe /mnt/atm/Windows/System32/' },
    { t: 'out', text: "'svchost32.exe' -> '/mnt/atm/Windows/System32/svchost32.exe' (847360 bytes)", s: 'ok' },
    { t: 'cmd', text: 'chntpw -e /mnt/atm/Windows/System32/config/SOFTWARE' },
    { t: 'out', text: '> ed Userinit' },
    { t: 'out', text: 'userinit.exe,C:\\Windows\\System32\\svchost32.exe', s: 'ann' },
    { t: 'out', text: '[ PERSISTENCE ] Winlogon\\Userinit autorun key modified', s: 'hi' },
    { t: 'cmd', text: 'sync && umount /mnt/atm' },
    { t: 'out', text: 'umount: /mnt/atm: clean - reinstall drive in bay', s: 'ok' },
  ],
  'install-method:2': [
    { t: 'cmd', text: 'lsusb | grep -i kingston' },
    { t: 'out', text: 'Bus 001 Device 003: ID 0951:1666 Kingston DataTraveler 32GB', s: 'ok' },
    { t: 'out', text: '# BIOS USB-first set - ATM will boot installer stick', s: 'ok' },
    { t: 'cmd', text: './ploutus-installer.sh --target ntfs --persist userinit' },
    { t: 'out', text: '[*] mounting NTFS via live OS...' },
    { t: 'out', text: '[*] payload written; Userinit patched', s: 'ok' },
    { t: 'out', text: '[ PERSISTENCE ] Winlogon\\Userinit modified', s: 'hi' },
  ],
  'install-method:3': [
    { t: 'out', text: '# blackbox: RPi Zero W + CDM firmware shim', s: 'ann' },
    { t: 'out', text: '# splice dispenser control cable behind safe door', s: 'ok' },
    { t: 'out', text: '# inline between ATM CPU and CDM module', s: 'ok' },
    { t: 'out', text: '# intercept/replay WFSExecute CDM_DISPENSE', s: 'ok' },
    { t: 'out', text: '# no malware / no reboot / CPU never sees payload', s: 'hi' },
    { t: 'out', text: '# trigger: encrypted SMS to onboard SIM', s: 'ok' },
  ],
  'persist-method:1': [
    { t: 'cmd', text: 'echo "reseal; unclamp; power-cycle"' },
    { t: 'out', text: 'reseal; unclamp; power-cycle', s: 'ok' },
    { t: 'cmd', text: 'cat /tmp/atm-serial.log' },
    { t: 'out', text: 'BIOS POST... OK' },
    { t: 'out', text: 'Windows XP loading...' },
    { t: 'out', text: 'Winlogon: executing userinit.exe' },
    { t: 'out', text: 'Winlogon: executing svchost32.exe  <- PLOUTUS-D LOADING', s: 'warn' },
    { t: 'out', text: 'ATM service: Agilis XFS started' },
    { t: 'out', text: 'ATM UI: ready for customer', s: 'ok' },
    { t: 'out', text: '# ploutus-d resident; waits on external USB keyboard', s: 'ok' },
  ],
  'activate-method:1': [
    { t: 'cmd', text: 'echo "mule1 on-site; USB HID keyboard attached"' },
    { t: 'out', text: 'mule1 on-site; USB HID keyboard attached', s: 'ok' },
    { t: 'cmd', text: 'cat codes/today.txt' },
    { t: 'out', text: 'X9K2-M7PQ-4RNS-8WBT-C3LF-6YDV', s: 'warn' },
    { t: 'out', text: '# rotating activation code accepted', s: 'ok' },
    { t: 'cmd', text: 'cat /proc/ploutus/menu' },
    { t: 'out', text: '[F1] DISPENSE CASSETTE 1   [F2] DISPENSE CASSETTE 2', s: 'ann' },
    { t: 'out', text: '[F3] DISPENSE CASSETTE 3   [F4] DISPENSE ALL CASSETTES', s: 'ann' },
    { t: 'out', text: '# mule selects F4 - DISPENSE ALL CASSETTES', s: 'warn' },
  ],
};

export const ATM_INITIAL: AtmVisualState = {
  panelOpen: false,
  ethState: 'intact',
  driveState: 'present',
  showLaptop: false,
  showBlackbox: false,
  screenMode: 'normal',
  showExtKeyboard: false,
  dispensing: false,
  showCassetteCutaway: false,
  showMule: false,
  showClamp: false,
  accessMethod: null,
  showUsbStick: false,
  showSensorCut: false,
  showDoorAjar: false,
  showPhone: false,
  showTamperTape: false,
};

export const PHASE_LINES: Record<number, TermLine[]> = {
  1: [
    { t: 'cmd', text: 'ls ~/drop' },
    { t: 'out', text: 'bootstrap.sh  tools/  .oprc' },
    { t: 'blank' },
    { t: 'cmd', text: 'sudo ./drop/bootstrap.sh' },
    { t: 'out', text: '[sudo] password for danny: ********' },
    { t: 'blank' },
    { t: 'out', text: '[*] Train de Aqua // bootstrap v0.9.4', s: 'ann' },
    { t: 'out', text: '[*] verifying drop signature… OK (ed25519)', s: 'ok' },
    { t: 'out', text: '[*] mounting operator overlay → /root/ploutus', s: 'ok' },
    { t: 'out', text: '[*] seeding recon notes, payload tree, codes/', s: 'ok' },
    { t: 'out', text: '[*] switching uid=0 cwd=/root/ploutus', s: 'ok' },
    { t: 'out', text: "# welcome aboard. don't get cute with random cmds once you're in.", s: 'warn' },
    { t: 'blank' },
    { t: 'banner' },
    { t: 'out', text: '// PHASE 01 - RECON', s: 'ann' },
    { t: 'blank' },
    { t: 'out', text: '# on-site: laptop plugged into branch LAN (same subnet as ATM)' },
    { t: 'cmd', text: 'ip -4 addr show eth0 | grep inet' },
    { t: 'out', text: '    inet 192.168.1.104/24 brd 192.168.1.255 scope global eth0' },
    { t: 'cmd', text: 'ip route | head -n1' },
    { t: 'out', text: 'default via 192.168.1.1 dev eth0 proto dhcp' },
    { t: 'blank' },
    { t: 'cmd', text: 'nmap -sV -p8080 --open 192.168.1.0/24' },
    { t: 'out', text: 'Starting Nmap 7.94 ( https://nmap.org )' },
    { t: 'out', text: 'Nmap scan report for 192.168.1.47' },
    { t: 'out', text: 'Host is up (0.0042s latency).' },
    { t: 'out', text: 'PORT     STATE SERVICE VERSION' },
    { t: 'out', text: '8080/tcp open  http    Agilis ATM XFS 3.20' },
    { t: 'out', text: 'Service Info: OS: Windows XP Professional SP3; CPE: cpe:/o:microsoft:windows_xp' },
    { t: 'blank' },
    { t: 'cmd', text: 'curl -s http://192.168.1.47/status | python3 -m json.tool' },
    { t: 'out', text: '{' },
    { t: 'out', text: '    "model": "Optiva740",' },
    { t: 'out', text: '    "vendor": "Dyebold",' },
    { t: 'out', text: '    "cassettes": 4,' },
    { t: 'out', text: '    "firmware": "3.20.4",' },
    { t: 'out', text: '    "xfs": "Kalignite"' },
    { t: 'out', text: '}' },
    { t: 'blank' },
    { t: 'cmd', text: 'cat recon/target.md' },
    { t: 'out', text: '# target: Dyebold Optiva 740 AFD - 4 cassettes (~$50K ea)' },
    { t: 'out', text: '# os: Windows XP SP3 - EOL, unpatched since 2014-04' },
    { t: 'out', text: '# attack: CDM_DISPENSE via MSXFS.dll (Agilis XFS 3.20)' },
    { t: 'out', text: '# camera blind: NW vestibule corner 02:00-05:30' },
    { t: 'out', text: '# kit: T-bar SKU 001-0006522, Ploutus-D build, 2 mules on standby' },
    { t: 'blank' },
    { t: 'out', text: '[ RECON COMPLETE ] Proceeding to breach...', s: 'hi' },
  ],
  2: [
    { t: 'out', text: '// PHASE 02 - BREACH', s: 'ann' },
    { t: 'blank' },
    { t: 'cmd', text: 'echo "vestibule clear - DN tech cover ready"' },
    { t: 'out', text: 'vestibule clear - DN tech cover ready', s: 'ok' },
    { t: 'blank' },
    { t: 'choice', id: 'panel-access' },
    { t: 'blank' },
    { t: 'choice', id: 'ethernet' },
    { t: 'blank' },
    { t: 'choice', id: 'alarm-sensor' },
    { t: 'blank' },
    { t: 'cmd', text: 'echo "[*] internal access confirmed"' },
    { t: 'out', text: '[*] internal access confirmed', s: 'ok' },
    { t: 'blank' },
    { t: 'out', text: '[ BREACH COMPLETE ] Proceeding to install...', s: 'hi' },
  ],
  3: [
    { t: 'out', text: '// PHASE 03 - INSTALL', s: 'ann' },
    { t: 'blank' },
    { t: 'cmd', text: 'lsblk -o NAME,SIZE,TYPE,MODEL | grep -E "NAME|sda|sdb"' },
    { t: 'out', text: 'NAME   SIZE TYPE MODEL' },
    { t: 'out', text: 'sdb     80G disk ATM-HDD-2.5SATA', s: 'ok' },
    { t: 'out', text: '# persistence target: Winlogon\\Userinit -> svchost32.exe', s: 'ok' },
    { t: 'blank' },
    { t: 'choice', id: 'install-method' },
    { t: 'blank' },
    { t: 'out', text: '[ INSTALL COMPLETE ] Closing cabinet...', s: 'hi' },
  ],
  4: [
    { t: 'out', text: '// PHASE 04 - PERSIST', s: 'ann' },
    { t: 'blank' },
    { t: 'out', text: '# payload on disk - choose how to leave the machine', s: 'ok' },
    { t: 'blank' },
    { t: 'choice', id: 'persist-method' },
    { t: 'blank' },
    { t: 'out', text: '[ PERSIST COMPLETE ] Mule team deploying...', s: 'hi' },
  ],
  5: [
    { t: 'out', text: '// PHASE 05 - ACTIVATE', s: 'ann' },
    { t: 'blank' },
    { t: 'out', text: '# ATM looks normal to customers - choose activation path', s: 'ok' },
    { t: 'blank' },
    { t: 'choice', id: 'activate-method' },
    { t: 'blank' },
    { t: 'out', text: '[ ACTIVATION COMPLETE ] Initiating dispense...', s: 'hi' },
  ],
  6: [
    { t: 'out', text: '// PHASE 06 - JACKPOT', s: 'ann' },
    { t: 'blank' },
    { t: 'cmd', text: 'dmesg | tail -n 8' },
    { t: 'out', text: 'ploutus: WFSExecute(hService, CDM_DISPENSE, pCDMDispense, 30000)', s: 'ann' },
    { t: 'out', text: 'cdm0: cassette1 $20  @100 npm - DISPENSING', s: 'ok' },
    { t: 'out', text: 'cdm0: cassette2 $50  @100 npm - DISPENSING', s: 'ok' },
    { t: 'out', text: 'cdm0: cassette3 $100 @100 npm - DISPENSING', s: 'ok' },
    { t: 'out', text: 'cdm0: cassette4 $100 @100 npm - DISPENSING', s: 'ok' },
  ],
};

export const NARRATIVES: Record<number, string> = {
  1: 'Attacker plugs into the branch LAN and maps the ATM on the same subnet - model, OS, XFS version, camera coverage.',
  2: 'Physical access at the machine. The ethernet loopback plug is critical - without it, the bank SIEM receives a live tamper alert.',
  3: 'Ploutus-D is deployed as a disguised Windows service and wired into the Winlogon autorun registry key. Survives reboots invisibly.',
  4: 'The ATM reboots normally. Customers use it. The bank sees nothing. Ploutus-D waits silently for an activation code.',
  5: 'The money mule arrives later with a pre-generated activation code. The hidden UI bypasses the entire transaction authorization system.',
  6: 'XFS CDM_DISPENSE is called directly - no bank authorization, no transaction record, no limit. $212,000 dispensed.',
};
