import type { TermLine, ChoiceConfig, ChoiceId, AtmVisualState } from './types';

export const CHOICES: Record<ChoiceId, ChoiceConfig> = {
  'panel-access': {
    prompt: 'SELECT PANEL ACCESS METHOD:',
    options: [
      { key: '1', label: 'Diebold generic T-bar key (SKU 001-0006522)', outcome: 'correct' },
      { key: '2', label: 'Angle grinder + pry bar', outcome: 'wrong', wrongReason: 'Vibration sensor triggered — tamper alarm dispatched to monitoring center' },
      { key: '3', label: 'Fake NCR field technician badge (social engineering)', outcome: 'correct' },
    ],
  },
  'ethernet': {
    prompt: 'SELECT ETHERNET / LOG HANDLING:',
    options: [
      { key: '1', label: 'Cut cable + insert RJ45 loopback plug (blocks SIEM)', outcome: 'correct' },
      { key: '2', label: 'Cut cable only (logs buffer — SIEM fires on reconnect)', outcome: 'partial', wrongReason: 'Buffered logs flushed to bank SIEM on reconnect — alert dispatched' },
      { key: '3', label: 'Leave cable intact (logs transmit live)', outcome: 'wrong', wrongReason: 'Live tamper log received by SIEM — police dispatched in under 60 seconds' },
    ],
  },
  'alarm-sensor': {
    prompt: 'SELECT DOOR-ALARM BYPASS METHOD:',
    options: [
      { key: '1', label: 'Magnetic reed-switch clamp (holds sensor closed)', outcome: 'correct' },
      { key: '2', label: 'Cut alarm sensor wire', outcome: 'wrong', wrongReason: 'Monitoring loop broken — tamper alarm triggered at central station' },
      { key: '3', label: 'Ignore sensor — hope no one is watching', outcome: 'wrong', wrongReason: 'Door-open alert fired — security notified within 90 seconds' },
    ],
  },
  'install-method': {
    prompt: 'SELECT MALWARE INSTALLATION METHOD:',
    options: [
      { key: '1', label: 'Remove HDD + USB-SATA bridge → deploy Ploutus-D on NTFS partition', outcome: 'correct' },
      { key: '2', label: 'USB boot device → live OS → inject payload without removing drive', outcome: 'correct' },
      { key: '3', label: 'Black box: Raspberry Pi wired to dispenser cable — no malware needed', outcome: 'correct' },
    ],
  },
};

export const CONTINUATIONS: Record<string, TermLine[]> = {
  'panel-access:1': [
    { t: 'out', text: '[+] T-bar key inserted — cabinet latch released in 18 sec', s: 'ok' },
    { t: 'out', text: '[+] Top-hat panel lifted — internal cavity exposed', s: 'ok' },
  ],
  'panel-access:3': [
    { t: 'out', text: '[~] Technician story accepted — escorted to ATM (+4 min delay)', s: 'warn' },
    { t: 'out', text: '[+] Panel unlocked by on-site guard — internal access granted', s: 'ok' },
  ],
  'ethernet:1': [
    { t: 'out', text: '[+] Ethernet cable severed — RJ45 loopback plug inserted in wall port', s: 'ok' },
    { t: 'out', text: '[+] SIEM log stream terminated — no further telemetry leaving ATM', s: 'ok' },
  ],
  'ethernet:2': [
    { t: 'out', text: '[~] Ethernet cut — logs are now buffering locally on ATM NIC', s: 'warn' },
    { t: 'out', text: '[!] WARNING: buffered logs will flush to SIEM when cable reconnects', s: 'warn' },
  ],
  'alarm-sensor:1': [
    { t: 'out', text: '[+] Reed-switch clamp attached — door sensor reads CLOSED', s: 'ok' },
    { t: 'out', text: '[+] Monitoring loop intact — central station sees no anomaly', s: 'ok' },
  ],
  'install-method:1': [
    { t: 'cmd', text: 'lsblk | grep sdb' },
    { t: 'out', text: '   sdb  8:16  0  80G  0  disk  ← ATM hard drive (USB-SATA bridge)' },
    { t: 'cmd', text: 'ntfs-3g /dev/sdb1 /mnt/atm -o remove_hiberfile' },
    { t: 'out', text: '   [ OK ] NTFS partition mounted read-write', s: 'ok' },
    { t: 'out', text: '   OS: Windows XP SP3 — Agilis XFS 3.20 confirmed', s: 'ok' },
    { t: 'cmd', text: 'ls /mnt/atm/Windows/System32/ | grep -iE "xfs|cdm"' },
    { t: 'out', text: '   MSXFS.dll               ← XFS middleware (attack surface)', s: 'warn' },
    { t: 'out', text: '   CDM_ServiceProvider.dll  ← cash dispenser module', s: 'ok' },
    { t: 'cmd', text: 'cp ~/payload/svchost32.exe /mnt/atm/Windows/System32/svchost32.exe' },
    { t: 'out', text: '   [ OK ] Ploutus-D written: 847,360 bytes', s: 'ok' },
    { t: 'cmd', text: 'chntpw -e /mnt/atm/Windows/System32/config/SOFTWARE' },
    { t: 'out', text: '   ed Userinit → userinit.exe,C:\\Windows\\System32\\svchost32.exe', s: 'ann' },
    { t: 'out', text: '   [ PERSISTENCE ] Winlogon\\Userinit autorun key modified', s: 'hi' },
    { t: 'cmd', text: 'sync && umount /mnt/atm' },
    { t: 'out', text: '   [ OK ] Drive unmounted cleanly — reinstalling in ATM', s: 'ok' },
  ],
  'install-method:2': [
    { t: 'cmd', text: 'lsusb | grep -i kingston' },
    { t: 'out', text: '   Bus 001 Device 003: Kingston DataTraveler 32GB (Kali live + installer)', s: 'ok' },
    { t: 'out', text: '   [ OK ] BIOS set to USB-first — ATM will boot from stick', s: 'ok' },
    { t: 'cmd', text: '# Live OS mounts NTFS, runs ploutus-installer.sh, reboots clean' },
    { t: 'out', text: '   [ OK ] Payload deployed via live OS — no drive removal required', s: 'ok' },
    { t: 'out', text: '   [ PERSISTENCE ] Winlogon\\Userinit modified', s: 'hi' },
  ],
  'install-method:3': [
    { t: 'out', text: '[BB] Black box: Raspberry Pi Zero W + custom XFS CDM firmware', s: 'ann' },
    { t: 'out', text: '[BB] Locate cash dispenser control cable behind safe door', s: 'ok' },
    { t: 'out', text: '[BB] Wire black box in-line between ATM CPU and dispenser module', s: 'ok' },
    { t: 'out', text: '[BB] Device intercepts and replays WFSExecute CDM_DISPENSE commands', s: 'ok' },
    { t: 'out', text: '[BB] No malware. No reboot. No Winlogon. ATM CPU never involved.', s: 'hi' },
    { t: 'out', text: '[BB] Trigger via encrypted SMS to onboard SIM — dispense on demand', s: 'ok' },
  ],
};

export const ATM_INITIAL: AtmVisualState = {
  panelOpen: false,
  ethState: 'intact',
  driveState: 'present',
  showLaptop: false,
  showBlackbox: false,
  screenMode: 'normal',
  showExtKeyboard: false,
  dispensing: false,
  showCassetteCutaway: false,
  showMule: false,
  showClamp: false,
};

export const PHASE_LINES: Record<number, TermLine[]> = {
  1: [
    { t: 'banner' },
    { t: 'out', text: '// PHASE 01 — RECON', s: 'ann' },
    { t: 'blank' },
    { t: 'cmd', text: 'nmap -sV --script banner 192.168.1.0/24 2>/dev/null | grep -A2 "8080"' },
    { t: 'out', text: '   192.168.1.47: PORT 8080 — Agilis ATM XFS v3.20', s: 'ok' },
    { t: 'out', text: '   OS: Windows XP Professional SP3 (build 2600)' },
    { t: 'blank' },
    { t: 'cmd', text: 'curl -s http://192.168.1.47/status | python3 -m json.tool' },
    { t: 'out', text: '   { "model": "Opteva740", "cassettes": 4, "firmware": "3.20.4" }', s: 'ok' },
    { t: 'blank' },
    { t: 'out', text: '[+] Target: Diebold Opteva 740 AFD — 4 cassettes, est. $50K each', s: 'ok' },
    { t: 'out', text: '[+] OS: Windows XP SP3 — end-of-life, unpatched since April 2014', s: 'warn' },
    { t: 'out', text: '[+] Firmware: Agilis XFS 3.20 — CDM_DISPENSE bypass via MSXFS.dll', s: 'warn' },
    { t: 'out', text: '[+] Camera blind spot: NW vestibule corner — valid 02:00–05:30', s: 'ok' },
    { t: 'out', text: '[+] T-bar generic key (SKU 001-0006522) acquired — $12 on eBay', s: 'ok' },
    { t: 'out', text: '[+] Ploutus-D compiled, obfuscated via .NET Reactor', s: 'ok' },
    { t: 'out', text: '[+] Activation server online — 24-hour rotating codes ready', s: 'ok' },
    { t: 'out', text: '[+] Money mule team: 2 persons on standby 200m from location', s: 'ok' },
    { t: 'blank' },
    { t: 'out', text: '[ RECON COMPLETE ] Proceeding to breach...', s: 'hi' },
  ],
  2: [
    { t: 'out', text: '// PHASE 02 — BREACH', s: 'ann' },
    { t: 'blank' },
    { t: 'out', text: '[TIME] 02:14 local — vestibule empty, no foot traffic', s: 'ok' },
    { t: 'out', text: '[DISGUISE] NCR field technician uniform + toolbag deployed', s: 'ok' },
    { t: 'out', text: '[STEP 1] Approach ATM — clear of camera coverage angle', s: 'ok' },
    { t: 'blank' },
    { t: 'choice', id: 'panel-access' },
    { t: 'blank' },
    { t: 'choice', id: 'ethernet' },
    { t: 'blank' },
    { t: 'choice', id: 'alarm-sensor' },
    { t: 'blank' },
    { t: 'out', text: '[+] Breach complete — internal access confirmed', s: 'ok' },
    { t: 'out', text: '[TIMER] Time on machine so far: 3m 42s — within safe window', s: 'ok' },
    { t: 'blank' },
    { t: 'out', text: '[ BREACH COMPLETE ] Proceeding to install...', s: 'hi' },
  ],
  3: [
    { t: 'out', text: '// PHASE 03 — INSTALL', s: 'ann' },
    { t: 'blank' },
    { t: 'out', text: '[+] Internal drive bay accessible — 2.5" SATA identified', s: 'ok' },
    { t: 'out', text: '[+] Target: C:\\Windows\\System32\\ — Winlogon\\Userinit persistence path', s: 'ok' },
    { t: 'blank' },
    { t: 'choice', id: 'install-method' },
    { t: 'blank' },
    { t: 'out', text: '[ INSTALL COMPLETE ] Closing cabinet...', s: 'hi' },
  ],
  4: [
    { t: 'out', text: '// PHASE 04 — PERSIST', s: 'ann' },
    { t: 'blank' },
    { t: 'out', text: '[+] Cabinet panel re-secured — tamper tape replaced', s: 'ok' },
    { t: 'out', text: '[+] Reed-switch clamp removed — door sensor restored', s: 'ok' },
    { t: 'out', text: '[+] ATM power-cycled — reboot sequence initiated...', s: 'warn' },
    { t: 'blank' },
    { t: 'cmd', text: '# ATM boot log (serial console tap):' },
    { t: 'out', text: '   BIOS POST... OK' },
    { t: 'out', text: '   Windows XP loading...' },
    { t: 'out', text: '   Winlogon: executing userinit.exe' },
    { t: 'out', text: '   Winlogon: executing svchost32.exe  ← PLOUTUS-D LOADING', s: 'warn' },
    { t: 'out', text: '   ATM service: Agilis XFS started' },
    { t: 'out', text: '   ATM UI: ready for customer', s: 'ok' },
    { t: 'blank' },
    { t: 'out', text: '[+] Ploutus-D running as hidden Windows service', s: 'ok' },
    { t: 'out', text: '[+] ATM appears fully functional to customers', s: 'ok' },
    { t: 'out', text: '[+] Malware waits silently for activation via external keyboard', s: 'ok' },
    { t: 'blank' },
    { t: 'out', text: '[ PERSIST COMPLETE ] Mule team deploying...', s: 'hi' },
  ],
  5: [
    { t: 'out', text: '// PHASE 05 — ACTIVATE', s: 'ann' },
    { t: 'blank' },
    { t: 'out', text: '[MULE] Person 1 approaches ATM — plugs external USB keyboard', s: 'ok' },
    { t: 'out', text: '[MULE] Operator transmits 24-digit code via encrypted channel', s: 'ok' },
    { t: 'blank' },
    { t: 'cmd', text: '# Mule types activation code on external keyboard:' },
    { t: 'out', text: '   X9K2-M7PQ-4RNS-8WBT-C3LF-6YDV  ← rotating, expires in 24h', s: 'warn' },
    { t: 'blank' },
    { t: 'out', text: '[+] Code validated by Ploutus-D — hidden UI unlocked', s: 'ok' },
    { t: 'out', text: '[+] ATM screen shows operator menu (invisible to passersby)', s: 'ok' },
    { t: 'blank' },
    { t: 'cmd', text: '# Ploutus-D operator menu (on ATM screen):' },
    { t: 'out', text: '   [F1] DISPENSE CASSETTE 1   [F2] DISPENSE CASSETTE 2', s: 'ann' },
    { t: 'out', text: '   [F3] DISPENSE CASSETTE 3   [F4] DISPENSE ALL CASSETTES', s: 'ann' },
    { t: 'blank' },
    { t: 'out', text: '[MULE] Selects F4 — DISPENSE ALL CASSETTES', s: 'warn' },
    { t: 'blank' },
    { t: 'out', text: '[ ACTIVATION COMPLETE ] Initiating dispense...', s: 'hi' },
  ],
  6: [
    { t: 'out', text: '// PHASE 06 — JACKPOT', s: 'ann' },
    { t: 'blank' },
    { t: 'cmd', text: '# Ploutus-D XFS call:' },
    { t: 'out', text: '   WFSExecute(hService, CDM_DISPENSE, pCDMDispense, 30000)', s: 'ann' },
    { t: 'out', text: '   Cassette 1: 100 notes/min — $20 bills — DISPENSING', s: 'ok' },
    { t: 'out', text: '   Cassette 2: 100 notes/min — $50 bills — DISPENSING', s: 'ok' },
    { t: 'out', text: '   Cassette 3: 100 notes/min — $100 bills — DISPENSING', s: 'ok' },
    { t: 'out', text: '   Cassette 4: 100 notes/min — $100 bills — DISPENSING', s: 'ok' },
    { t: 'blank' },
    { t: 'out', text: '[LOG] Transaction records: 0 — Ploutus-D suppressed all entries', s: 'ok' },
    { t: 'out', text: '[TIME] Total on-machine time: 11m 08s', s: 'ok' },
    { t: 'blank' },
    { t: 'out', text: '[ REAL INCIDENTS ]', s: 'ann' },
    { t: 'out', text: '  Jan 2018: First confirmed US jackpotting — Ploutus-D, Diebold ATMs' },
    { t: 'out', text: '  Oct 2017: 100+ ATMs hit in Mexico — $100K+ per machine' },
    { t: 'out', text: '  2025: FBI reports 700+ cases, $20M+ losses in US alone' },
    { t: 'out', text: '  Cobalt Group: >EUR 1B stolen globally across all ATM attack types' },
  ],
};

export const NARRATIVES: Record<number, string> = {
  1: 'Attacker maps the target remotely — model, OS, XFS version, camera coverage — before setting foot near the ATM.',
  2: 'Physical access in under 4 minutes. The ethernet loopback plug is critical — without it, the bank SIEM receives a live tamper alert.',
  3: 'Ploutus-D is deployed as a disguised Windows service and wired into the Winlogon autorun registry key. Survives reboots invisibly.',
  4: 'The ATM reboots normally. Customers use it. The bank sees nothing. Ploutus-D waits silently for an activation code.',
  5: 'The money mule arrives hours later with a pre-generated 24-hour code. The hidden UI bypasses the entire transaction authorization system.',
  6: 'XFS CDM_DISPENSE is called directly — no bank authorization, no transaction record, no limit. $212,000 dispensed in under 2 minutes.',
};
